<?php

namespace Vasoft\Joke\Tests\Core\Routing;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use stdClass;
use Vasoft\Joke\Core\Routing\Exceptions\AutowiredException;
use Vasoft\Joke\Core\Routing\ParameterResolver;
use Vasoft\Joke\Core\ServiceContainer;
use Vasoft\Joke\Tests\Fixtures\Service\SingleService;

include_once __DIR__ . '/FakeExample.php';

class ParameterResolverTest extends TestCase
{
    protected static ServiceContainer $serviceContainer;

    public static function setUpBeforeClass(): void
    {
        self::$serviceContainer = new ServiceContainer();
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function dataProviderClosure(): array
    {
        $testObject = new FakeExample(0);
        return [
            [
                function ($num, $page) {
                    return $num + $page;
                }
            ],
            [FakeExample::exampleClosureStatic(...),],
            [$testObject->exampleClosure(...)],
            ['\Vasoft\Joke\Tests\Core\Routing\FakeExample::exampleClosureStatic'],
            ['\Vasoft\Joke\Tests\Core\Routing\exampleClosureFunction'],
            [[FakeExample::class, 'exampleClosureStatic']],
            [[$testObject, 'exampleClosure']],
        ];
    }

    /**
     * @param $closure
     * @return void
     */
    #[DataProvider('dataProviderClosure')]
    public function testClosure($closure): void
    {
        $resolver = new ParameterResolver(self::$serviceContainer);
        self::assertEquals([2, 1], $resolver->resolveForCallable($closure, ['page' => 1, 'num' => 2]));
    }

    public function testResolveObject(): void
    {
        $callback = function (int $page, FakeExample $num) {
            return $page + $num->value;
        };
        $resolver = new ParameterResolver(self::$serviceContainer);
        $args = $resolver->resolveForCallable($callback, ['page' => 1, 'num' => 2]);
        self::assertInstanceOf(FakeExample::class, $args[1]);
    }

    public function testResolveObjectException(): void
    {
        $callback = function (int $a, stdClass $b) {
            return $a + $b->value;
        };
        $resolver = new ParameterResolver(self::$serviceContainer);
        self::expectException(AutowiredException::class);
        self::expectExceptionMessage(
            'Failed to autowire parameter "$b": expected type "stdClass" cannot be resolved or is incompatible with the provided value.'
        );
        $resolver->resolveForCallable($callback, ['b' => 1, 'a' => 2]);
    }

    public function testAutowiredService(): void
    {
        $callback = function (int $a, SingleService $b) {
            return $a + $b->getValue();
        };
        self::$serviceContainer->registerSingleton(SingleService::class, SingleService::class);
        $resolver = new ParameterResolver(self::$serviceContainer);
        $args = $resolver->resolveForCallable($callback, ['a' => 12]);
        self::assertCount(2, $args);
    }

    public function testAutowiredUnknown(): void
    {
        $callback = function (int $a, \SingleServiceUnknown $b) {
            return $a + $b->getValue();
        };
        $resolver = new ParameterResolver(self::$serviceContainer);
        self::expectException(AutowiredException::class);
        self::expectExceptionMessage(
            'Failed to autowire parameter "$b": expected type "SingleServiceUnknown" cannot be resolved or is incompatible with the provided value.'
        );
        $args = $resolver->resolveForCallable($callback, ['a' => 12]);
    }

    public function testAutowiredServiceNotRegistered(): void
    {
        $callback = function (int $a, FakeExample $b) {
            return $a + $b->value;
        };
        $resolver = new ParameterResolver(self::$serviceContainer);
        self::expectException(AutowiredException::class);
        self::expectExceptionMessage(
            'Failed to autowire parameter "$b": expected type "Vasoft\Joke\Tests\Core\Routing\FakeExample" cannot be resolved or is incompatible with the provided value.'
        );
        $resolver->resolveForCallable($callback, ['a' => 12]);
    }

    public function testAutowiredScalar(): void
    {
        $callback = function (int $a, $b) {
            return $a + $b->getValue();
        };
        $resolver = new ParameterResolver(self::$serviceContainer);
        self::expectException(AutowiredException::class);
        self::expectExceptionMessage(
            'Failed to autowire parameter "$b": expected type "scalar" cannot be resolved or is incompatible with the provided value.'
        );
        $resolver->resolveForCallable($callback, ['a' => 12]);
    }

    public function testResolveForConstructor(): void
    {
        $resolver = new ParameterResolver(self::$serviceContainer);
        $args = $resolver->resolveForConstructor(FakeExample::class, ['value' => 12, 'z' => 14]);
        self::assertCount(1, $args);
        self::assertEquals(12, $args[0]);
    }
}
