<?php

namespace Vasoft\Joke\Tests\Core\Routing;

use PHPUnit\Framework\Attributes\DataProvider;
use Vasoft\Joke\Core\Request\HttpMethod;
use Vasoft\Joke\Core\Request\HttpRequest;
use Vasoft\Joke\Core\Routing\Route;
use PHPUnit\Framework\TestCase;
use Vasoft\Joke\Core\ServiceContainer;
use Vasoft\Joke\Tests\Fixtures\Controllers\InvokeController;

include_once __DIR__ . '/FakeExample.php';

class RouteTest extends TestCase
{
    protected static ServiceContainer $serviceContainer;

    public static function setUpBeforeClass(): void
    {
        self::$serviceContainer = new ServiceContainer();
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function dataProviderRun(): array
    {
        $testObject = new  FakeExample(0);

        return [
            [
                function ($num, $page) {
                    return $num + $page;
                }
            ],
            [FakeExample::exampleClosureStatic(...),],
            [$testObject->exampleClosure(...)],
            ['\Vasoft\Joke\Tests\Core\Routing\FakeExample::exampleClosureStatic'],
            ['\Vasoft\Joke\Tests\Core\Routing\exampleClosureFunction'],
            [[FakeExample::class, 'exampleClosureStatic']],
            [[$testObject, 'exampleClosure']],
        ];
    }

    public function testCompilePattern(): void
    {
        $route = new Route(
            self::$serviceContainer,
            '/api/{section}/{num:int}/{page:int}/{filter:slug}',
            HttpMethod::GET,
            function () { }
        );
        self::assertSame(
            '#^/api/(?P<section>[^/]+)/(?P<num>\d+)/(?P<page>\d+)/(?P<filter>[a-z0-9\-_]+)$#i',
            $route->compiledPattern
        );
    }

    public function testWithMethod(): void
    {
        $route = new Route(self::$serviceContainer, '/', HttpMethod::GET, function () { });
        self::assertEquals(HttpMethod::GET, $route->method);
        $route2 = $route->withMethod(HttpMethod::POST);
        self::assertEquals(HttpMethod::POST, $route2->method);
        self::assertNotEquals($route, $route2);
    }

    public function testMatchesSuccess(): void
    {
        $route = new Route(
            self::$serviceContainer,
            '/api/{section}/{num:int}/{page:int}/{filter:slug}',
            HttpMethod::GET,
            function () { }
        );
        $request = new HttpRequest(server: [
            'REQUEST_URI' => '/api/orders/1/2/closed'
        ]);
        self::assertTrue($route->matches($request));
        self::assertEquals([
            'section' => 'orders',
            'num' => 1,
            'page' => 2,
            'filter' => 'closed',
        ], $request->props->getAll());
    }

    public function testMatchesFail(): void
    {
        $route = new Route(
            self::$serviceContainer,
            '/api/{section}/{num:int}/{page:int}/{filter:slug}',
            HttpMethod::GET,
            function () { }
        );
        $request = new HttpRequest(server: [
            'REQUEST_URI' => '/rest/orders/1/2/closed'
        ]);
        self::assertFalse($route->matches($request));
    }

    #[DataProvider('dataProviderRun')]
    public function testRun($closure): void
    {
        $route = new Route(self::$serviceContainer, '/api/{num:int}/{page:int}', HttpMethod::GET, $closure);
        $request = new HttpRequest(server: ['REQUEST_URI' => '/api/1/2']);
        $route->matches($request);
        self::assertEquals(3, $route->run($request));
    }

    public function testInvoke(): void
    {
        $route = new Route(self::$serviceContainer, '/invoke/{prop}', HttpMethod::GET, InvokeController::class);
        $request = new HttpRequest(server: ['REQUEST_URI' => '/invoke/property']);
        $route->matches($request);
        self::assertEquals([
            'ServiceContainer' => spl_object_id(self::$serviceContainer),
            'propValue' => 'property',
        ], $route->run($request));
    }

    public function testMergeGroups(): void
    {
        $route = new Route(self::$serviceContainer, '/invoke/{prop}', HttpMethod::GET, InvokeController::class);
        $route->addGroup('test1');
        self::assertSame(['test1'], $route->getGroups());
        $route->mergeGroup(['test1', 'test2']);
        self::assertSame(['test1', 'test2'], $route->getGroups());
    }
}
